using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Catalyst {

    // The name of the catalyst (this should be generated by the factory)
    public string name;

    // The effects of the catalyst
    public List<CatalystEffect> effects = new List<CatalystEffect>();

    // The stats adjustment this catalyst should apply
    public Stats statsAdjustment;

    // The rarity of the catalyst
    public Rarities rarity;
}
