using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Catalyst {
    
    // Unique ID of the catalyst
    public uint id;

    // The name of the catalyst (this should be generated by the factory)
    public string name;


    // The effects of the catalyst
    public List<CatalystEffect> effects = new List<CatalystEffect>();


    // The stats adjustment this catalyst should apply
    public Stats statsAdjustment;


    // The rarity of the catalyst
    public Rarities rarity;


    // The model index to use
    public int modelVariantIndex = 1;
    
    // The ID of the last created catalyst
    public static uint LastCreatedID;
    
    // The slot this catalyst fits into
    public PetBodySlot slot;
}

public enum PetBodySlot
{
    Head,
    Body,
    Tail,
    Legs
}
